In [2]:
import numpy as np

In [43]:
np.zeros((2, (3, 4)))

TypeError: 'tuple' object cannot be interpreted as an integer

In [3]:
def gaussian_probability(mean, var, x):
    return 1 / np.sqrt(2 * np.pi * var) * np.exp(-(x - mean)**2 / (2 * var))

In [26]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

mean = np.array([1, 0.34, 0.014])

var = np.array([0.09, 0.001, 0.021])

gp = gaussian_probability(mean, var, X)
product = np.prod(gp, axis=1)

gp, product, np.argmin(gp, axis=1)
# np.concatenate([mean, var], axis=1)

(array([[1.32980760e+00, 0.00000000e+00, 1.75089221e-92],
        [2.56486621e-22, 0.00000000e+00, 0.00000000e+00]]),
 array([0., 0.]),
 array([1, 1]))