In [2]:
import numpy as np

In [13]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

mean = np.mean(X, axis=0)

var = np.var(X, axis=0)

print(mean)
print(var)

[2.5 3.5 4.5]
[2.25 2.25 2.25]


In [10]:
a = np.array([[1, 0, 0, 0, 2],
              [2, 1, 1, 1, 8]])


array([[1, 0],
       [0, 0],
       [2, 2],
       [1, 1],
       [1, 8]])